#ifndef DEFINES_H
#define DEFINES_H

#define MKSBMLP_MAX_LINE_LENGTH 20480

#define MKSBMLP_NO_ERROR 0
#define MKSBMLP_INVALID_PARAMETER -1
#define MKSBMLP_UNSPECIFIED_ERROR -2
#define MKSBMLP_TOO_MANY_XML_FILES -3

#define TOP_BOTTOM_CUTOFF 64.0f
#define TOP_BOTTOM_CUTOFF_HALF 32.0f

#define MKSBMLP_MAJOR_VERSION 0
#define MKSBMLP_MINOR_VERSION 9
#define MKSBMLP_PATCH_VERSION 0

#endif // DEFINES_H
