#ifndef MKSBULLETMLINTERPRETER_H
#define MKSBULLETMLINTERPRETER_H

#ifdef _WIN32
  #define EXPORT __declspec(dllexport)
#else
  #define EXPORT __attribute__((visibility("default")))
#endif

#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <libxml/parser.h>
#include <libxml/tree.h>

typedef unsigned int MKSBMLI_PLAYBACK_HANDLE;
typedef unsigned int MKSBMLI_BULLET_HANDLE;

#define MKSBMLI_MAX_PLAYBACK_HANDLES 1000
#define MKSBMLI_XML_FILENAME_MAX_LENGTH 2048
#define MKSBMLI_MAX_BULLETS 5000
#define MKSBMLI_MAX_ELEMENTS 500
#define MKSBMLI_MAX_TEXT_LENGTH 128

#define MKSBMLI_NO_ERROR 0
#define MKSBMLI_UNSPECIFIED_ERROR -1
#define MKSBMLI_XML_FILE_LOAD_ERROR -100
#define MKSBMLI_TOO_MANY_XML_FILES -101
#define MKSBMLI_XML_FILENAME_TOO_LONG -102
#define MKSBMLI_INVALID_XML_FILENAME -103
#define MKSBMLI_XML_PARSE_ERROR -104
#define MKSBMLI_TOO_MANY_BULLETS -105
#define MKSBMLI_ALREADY_PLAYING -120
#define MKSBMLI_NOT_PLAYING -121
#define MKSBMLI_INVALID_HANDLE -130
#define MKSBMLI_INVALID_PARAMETER -131

typedef enum {
    BULLETML_ATTRIBUTE_TYPE_NONE,
    BULLETML_ATTRIBUTE_TYPE_VERTICAL,
    BULLETML_ATTRIBUTE_TYPE_HORIZONTAL,
} BULLETML_ATTRIBUTE_TYPE;

typedef enum {
    BULLETML_ELEMENT_TYPE_NONE,
    BULLETML_ELEMENT_TYPE_BULLETML,
    BULLETML_ELEMENT_TYPE_BULLET,
    BULLETML_ELEMENT_TYPE_ACTION,
    BULLETML_ELEMENT_TYPE_FIRE,
    BULLETML_ELEMENT_TYPE_CHANGE_DIRECTION,
    BULLETML_ELEMENT_TYPE_CHANGE_SPEED,
    BULLETML_ELEMENT_TYPE_ACCEL,
    BULLETML_ELEMENT_TYPE_WAIT,
    BULLETML_ELEMENT_TYPE_VANISH,
    BULLETML_ELEMENT_TYPE_REPEAT,
    BULLETML_ELEMENT_TYPE_DIRECTION,
    BULLETML_ELEMENT_TYPE_SPEED,
    BULLETML_ELEMENT_TYPE_HORIZONTAL,
    BULLETML_ELEMENT_TYPE_VERTICAL,
    BULLETML_ELEMENT_TYPE_TERM,
    BULLETML_ELEMENT_TYPE_TIMES,
    BULLETML_ELEMENT_TYPE_BULLET_REF,
    BULLETML_ELEMENT_TYPE_ACTION_REF,
    BULLETML_ELEMENT_TYPE_FIRE_REF,
    BULLETML_ELEMENT_TYPE_PARAM,
} BULLETML_ELEMENT_TYPE;

typedef enum {
    AARS_TYPE_AIM,
    AARS_TYPE_ABSOLUTE,
    AARS_TYPE_RELATIVE,
    AARS_TYPE_SEQUENCE,
} AARS_TYPE;

typedef enum {
    ARS_TYPE_ABSOLUTE,
    ARS_TYPE_RELATIVE,
    ARS_TYPE_SEQUENCE,
} ARS_TYPE;

EXPORT int mksbmli_init();
EXPORT int mksbmli_shutdown();

EXPORT int mksbmli_set_random_seed(int seed);

EXPORT int mksbmli_load_xml(const char* xml_filename, MKSBMLI_PLAYBACK_HANDLE* handle);
EXPORT int mksbmli_unload_xml(MKSBMLI_PLAYBACK_HANDLE handle);
EXPORT int mksbmli_count_xmls();

EXPORT void mksbmli_start_playback(MKSBMLI_PLAYBACK_HANDLE handle);
EXPORT void mksbmli_stop_playback(MKSBMLI_PLAYBACK_HANDLE handle);
EXPORT bool mksbmli_is_playing(MKSBMLI_PLAYBACK_HANDLE handle);
EXPORT void mksbmli_next_frame(MKSBMLI_PLAYBACK_HANDLE handle);

EXPORT int mksbmli_get_bullets();
EXPORT int mksbmli_delete_bullets();

#endif // MKSBULLETMLINTERPRETER_H
